select * from table_main;

describe table_main;

/*WHEN RENAMING A COLUMN, YOU MUST INDICATE THE DATA TYPE OF THE NEW COLUMN*. 
THUS IT IS GOOD PRACTICE TO DESCRIBE THE TABLE FIRST AND UNDERSTAND THE AFFECTED COLUMN'S DATA TYPE.
*/
alter table table_main 
change column_1 column_0 int;

# THE COLUMN HAS NO BEEN RENAMED TO COLUMN_0 FROM COLUMN_1